# A new namespace to isolate our test
apiVersion: v1
kind: Namespace
metadata:
  name: quota-example
---

# The ResourceQuota Object
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-quota
  namespace: quota-example #Apply this quota to the 'quota-example' namespace
spec:
  hard:
    # Limit the number of objects that can be created
    pods: "2"
    configmaps: "2"
    secrets: "1"
    # Limit the total amount of compute resources
    requests.memory: "1Gi" # Sum of all container memory requests cannot exceed 1Gi
    limits.cpu: "2" # Sum of all container CPU limits cannot exceed 2 cores