apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
  - name: app-containers
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      # Requests and Limits are identical for both CPU and Memory
      # This configuration results in the 'Guaranteed' QoS class
      requests:
        memory: "100Mi"
        cpu: "100m" # 100 milliCPU (0.1 CPU)
      limits:
        memory: "100Mi"
        cpu: "100m" # 100 milliCPU (0.1 CPU)
