apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      # Limits are higher than requests.
      # The container is guaranteed its 'requests' but can 'burst' up to its 'limits'.
      # if resources are available. This results the 'Burstable' QoS class.
      requests:
        memory: "100Mi"
        cpu: "100m" # 100 milliCPU (0.1 CPU)
      limits:
        memory: "200Mi"
        cpu: "200m"